### ISSUE TITLE
Convert discriminator from uint16 to string

### ISSUE THREAD

**Issue by dadamu** [desmos-labs/hephaestus#2]
## Feature description 

Currently, The disclaimer of [`GetUsername`](https://github.com/desmos-labs/hephaestus/blob/18384b3aca0ec10e4b62f81e172c400c57c9bbc3/utils/discord.go#L10) is uint16 type. So, if the user has the disclaimer "#0001" then the username will be got as "User#1". It might confuse the user when creating the app link.

## Implementation proposal

Convert disclaimer from uint16 to string with by method [String()](https://github.com/andersfylling/disgord/blob/ef261f400c173ca921a1092f67c05094940c8259/struct.go#L252).

**Comment by rmontagnin** [comment]
Fixed with bc465444e36f4d46c8eb677e3bcc7fd06752c12b
